<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EducaWebApi.Data\EducaWebApi.Data.csproj" />
    <ProjectReference Include="..\EducaWebApi.Domain\EducaWebApi.Domain.csproj" />
  </ItemGroup>

</Project>
